---
- debug:
    var: tmpdir_root
    verbosity: 2

- debug:
    var: tmpdir_template
    verbosity: 2

- name: Create temporary directory
  block:
    - name: Create directory
      tempfile:
        state: directory
      register: tmpdir_tempfile
      notify:
        - tmpdir remove
    - name: Set tmpdir_path variable
      set_fact:
        tmpdir_path: "{{ tmpdir_tempfile.path }}"
  when: not tmpdir_path

- debug:
    var: tmpdir_path
    verbosity: 2
