## Tasks for the tmpdir role.
##
- debug:
    var: tmpdir_root
  tags:
    - debug

- debug:
    var: tmpdir_template
  tags:
    - debug

- name: create temporary directory
  command: "mktemp -d {{ tmpdir_root }}/{{ tmpdir_template }}"
  register: tmpdir_mktemp
  notify: 
    - tmpdir remove
  when: not tmpdir_path

- name: set tmpdir_path
  set_fact:
    tmpdir_path: "{{ tmpdir_mktemp.stdout }}"
  when: not tmpdir_path

- debug:
    var: tmpdir_path
  tags:
    - debug
