## Tasks for the tmpdir role.
##
- debug:
    var: tmpdir_root
  when: tmpdir_debug

- debug:
    var: tmpdir_template
  when: tmpdir_debug

- name: create temporary directory
  command: "mktemp -d {{ tmpdir_root }}/{{ tmpdir_template }}"
  notify: remove temporary directory
  register: mktemp

- name: export directory name
  set_fact:
    tmpdir_path: "{{ mktemp.stdout }}"
    
- debug:
    var: tmpdir_path
  when: tmpdir_debug
