## Handlers for the tmpdir task.
##
- name: remove temporary directory
  file: 
    path: "{{ tmpdir_path }}"
    state: absent
  notify:
  - unset tmpdir_path

- name: unset tmpdir_path
  set_fact:
    tmpdir_path: ""
