---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: EL7
    image: centos:7
  - name: Xenial
    image: ubuntu:16.04
  - name: Bionic
    image: ubuntu:18.04
  - name: Focal
    image: ubuntu:20.04
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    # Override default sequence to skip idempotence command.
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
