- hosts: all

  roles:
    - name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
    - name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"  # test multiple inclusion

  pre_tasks:
    - name: Create root directory
      file:
        path: "{{ tmpdir_root }}"
        state: directory

  post_tasks:
    - name: Verify that directory does not exist
      stat:
        path: "{{ tmpdir_path }}"
      register: task
      failed_when: task.stat.exists
    - name: Verify that tmpdir_path is unset
      fail:
        msg: "tmpdir_path: '{{ tmpdir_path }}'"
      when: tmpdir_path|bool
